### ISSUE TITLE
Enhance doc for du check

### ISSUE THREAD

**Issue by p-thurner** [satellitesharing/bloonix-plugins-satellitesharing#27]
when I go to /#monitoring/hosts/19/services/create, I am currently required to state a result-filename.

I would suggest the following:
- we "hardcore" a specific directory for result files following debian defaults (as we only package for deb based distros anyway), like `/var/cache/bloonix/du_my_identifyer.json`. This way the user doesnt "has to decide" - better imho in this case, the plugins should be easy and fast to use.
- in the WebUI when creating a check, I specify a unique name for the particular du check
- When creating the cronjob web could pass this as an argument `* */1 * * * /path/to/du-check-cronjob my_identifyer /path/to/du/directory`

I also couldnt find the cron-du script after installing the bloonix-plugins-satellitesharing-du package. There should also be a bit more doc in the webui when creating a check, sth like:

This check requires a cronjob to regularily check the size of a particular directory. The bloonix check will then read a results file created by that cronjob. To create such a cronjob, use `* */1 * * * /path/to/cron-du my_identifyer /path/to/dir` and specify `my_identifyer` in the options below.

**Comment by ehalm** [comment]
https://github.com/satellitesharing/bloonix-plugins-satellitesharing/commit/8bc208146bfd69fb3f0e2d12392b49d975393032

Done. Updated documentation and cron and agent code.
Result filenames are: /var/cache/bloonix/du_<identifier>.txt
The extension is 'txt' and not 'json' because though the data looks like JSON, it isn't JSON.
