### ISSUE TITLE
add doc to the ssllabs check

### ISSUE THREAD

**Issue by p-thurner** [satellitesharing/bloonix-plugins-satellitesharing#29]
Please add this doc to /#monitoring/hosts/19/services/create:

This check requires for you to setup a cronjob like `* */3 * * * /path/to/ssllabs-cron www.example.com`. For the cronjob to work, you are required to install the ssllabs-scan utility from https://github.com/ssllabs/ssllabs-scan on the machine that runs the agent that has to execute the cronjob.

Note that using `www.example.com` will create a results file in `/var/lib/bloonix/ssllabs_www.example.com.json` that is read by this check.

Also the cronjob is not included in bloonix-plugins-satellitesharing-ssllabs 0.4-1.

**Comment by ehalm** [comment]
https://github.com/satellitesharing/bloonix-plugins-satellitesharing/commit/94a9d09dab30213cd980d24ee9de0944d2fbc42c
