### ISSUE TITLE
Stick to a certain range for the plugin IDs

### ISSUE THREAD

**Issue by p-thurner** [satellitesharing/bloonix-plugins-satellitesharing#8]
I think we should declare a certain range of plugin IDs we intend to use so other people wont use the same as we do.

**Comment by ehalm** [comment]
The latest set use the 41100XX range. 
I'll update the php-fpm, asn, and varnish4 plugins to conform to that range.

**Comment by ehalm** [comment]
Just saw the satsharing README about the plugin IP range so will do the opposite update and make the new set conform to the range 3.000.000 to 3.010.000

**Comment by ehalm** [comment]
Done
